import { Platform, StyleSheet } from 'react-native';
import { shadowCircleButton, shadowFab, shadowSoft } from '../../theme/shadows';
import { HEADER_CIRCLE_BTN_SIZE } from '../../theme/layout';
import { TASK_FONT_SIZE_TITLE } from '../../theme/typography';
import type { AppColors } from '../../theme/appColors';

export function createChatStyles(c: AppColors) {
  return StyleSheet.create({

  container: { flex: 1, backgroundColor: c.background },
  containerInner: { flex: 1 },
  keyboardView: { flex: 1 },
  scrollAndGradientWrap: { flex: 1, position: 'relative' },
  historyLoadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: c.overlayScrim,
    zIndex: 20,
  },
  bottomOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 10,
  },
  bottomOverlayInner: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'column',
    justifyContent: 'flex-end',
  },
  /** 底部留白留给绝对定位的模型/助手/用量条（与改前「模型贴在输入区底」同一思路，不把整块顶高） */
  inputRowInOverlay: {
    position: 'relative',
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 12,
    paddingBottom: 26,
    gap: 12,
    overflow: 'visible',
  },
  /** 叠在输入行底部留白内；paddingLeft 与 scrollContent(28) 对齐；paddingRight 较小让右侧用量更贴屏缘 */
  composerMetaRowAbsolute: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 6,
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 32,
    paddingRight: 32,
    gap: 8,
  },
  composerMetaPills: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'nowrap',
    gap: 10,
  },
  composerMetaChip: {
    flexShrink: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  composerMetaChipReadonly: {
    flexShrink: 1,
    minWidth: 0,
    justifyContent: 'flex-start',
  },
  composerAgentReadonlyText: {
    fontSize: 11,
    color: c.textMuted,
  },
  composerUsageInMetaRow: {
    flexShrink: 0,
    maxWidth: '42%',
    alignItems: 'flex-end',
  },
  topBar: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    /** 须高于 historyLoadingOverlay(20)，拉历史时仍可点返回 / 标题区 / 加号 */
    zIndex: 30,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingBottom: 12,
  },
  circleBtn: {
    width: HEADER_CIRCLE_BTN_SIZE,
    height: HEADER_CIRCLE_BTN_SIZE,
    borderRadius: HEADER_CIRCLE_BTN_SIZE / 2,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: c.surface,
    ...shadowCircleButton,
  },
  leftEdgeGesture: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 24,
    /** 须高于 historyLoadingOverlay(20)，否则拉历史时全屏遮罩会挡住侧滑返回 */
    zIndex: 30,
  },
  headerTitleWrap: {
    flex: 1,
    minWidth: 0,
    justifyContent: 'center',
    alignItems: 'flex-start',
    paddingHorizontal: 8,
  },
  headerTitle: { fontSize: TASK_FONT_SIZE_TITLE, fontWeight: '700', color: c.textHeader },
  /** 与 composerUsageText 同档：小号、灰色、常规字重 */
  composerModelTriggerText: {
    flexShrink: 1,
    fontSize: 11,
    color: c.textMuted,
  },
  composerUsageText: {
    fontSize: 11,
    color: c.textMuted,
    textAlign: 'right',
    maxWidth: '100%',
  },
  globalError: { color: c.danger, fontSize: 13, paddingHorizontal: 28, paddingVertical: 8 },
  scroll: { flex: 1 },
  scrollContent: {
    paddingHorizontal: 28,
    paddingVertical: 20,
    paddingBottom: 32,
    alignItems: 'center',
  },
  chatContentWrap: {
    width: '100%',
    maxWidth: 380,
  },
  emptyStage: { flex: 1, paddingVertical: 40 },
  welcomeTitle: { fontSize: 22, fontWeight: '700', color: c.textHeader, marginBottom: 8 },
  welcomeSubtitle: { fontSize: 15, color: c.textMuted },
  bubbleWrap: { marginBottom: 18 },
  userBubbleWrap: { alignItems: 'flex-end' },
  assistantBubbleWrap: { width: '100%' },
  bubble: {
    maxWidth: '85%',
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 14,
  },
  userBubble: { backgroundColor: c.userBubble },
  assistantBubble: {
    width: '100%',
    maxWidth: '100%',
    backgroundColor: 'transparent',
    borderWidth: 0,
    borderRadius: 0,
    paddingVertical: 10,
    paddingHorizontal: 4,
  },
  bubbleRole: { fontSize: 12, color: c.textMuted, marginBottom: 6 },
  userText: { fontSize: 16, color: c.onPrimary },
  assistantText: { fontSize: 16, color: c.textPrimary, lineHeight: 24 },
  streamStatus: { fontSize: 14, color: c.textMuted, fontStyle: 'italic' },
  errorWrap: { marginBottom: 18, padding: 14, backgroundColor: c.errorBg, borderRadius: 8 },
  errorText: { color: c.danger, fontSize: 14 },
  assistantTextBlock: { marginTop: 10 },
  assistantTextBlockCompactAbove: { marginTop: 8 },
  /** 与 Web .assistant-empty-reply-block .markdown-content 一致，仅弱化提示正文 */
  assistantEmptyReplyMarkdownContent: { opacity: 0.62 },
  toolPackageNavLine: {
    marginTop: -4,
    paddingVertical: 2,
  },
  toolPackageNavLineText: {
    fontSize: 12,
    color: c.placeholder,
    lineHeight: 18,
  },
  toolCard: {
    marginTop: 4,
    marginBottom: 4,
    marginLeft: 0,
    marginRight: 0,
    padding: 14,
    backgroundColor: c.toolCardBg,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: c.borderMuted,
  },
  toolCardCollapsed: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 36,
    minWidth: 0,
  },
  toolCardCollapsedPressed: { backgroundColor: c.borderMuted },
  /** 单行折叠：占满徽章左侧剩余宽度，避免标题过长把「成功」顶出卡片 */
  toolCardCollapsedMain: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 6,
  },
  toolCardCollapsedName: {
    fontSize: 12,
    fontWeight: '600',
    color: c.textDark,
    marginRight: 8,
    flexShrink: 1,
    minWidth: 0,
  },
  toolCardCollapsedTail: {
    flex: 1,
    minWidth: 0,
    fontSize: 11,
    color: c.textMutedSlate,
    marginRight: 0,
  },
  toolCardBadgeWrap: { marginLeft: 4, flexShrink: 0 },
  toolCardBadge: {
    fontSize: 11,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: c.borderD4,
    color: c.textLabel,
    backgroundColor: c.borderMuted,
  },
  toolCardBadgeOk: {
    color: c.textSecondary,
    backgroundColor: c.borderMuted,
    borderColor: c.borderD4,
  },
  toolCardBadgeSuccess: {
    color: c.textSecondary,
    backgroundColor: c.borderMuted,
    borderColor: c.borderD4,
  },
  toolCardContentPressed: { opacity: 0.95 },
  toolCardExpandRow: {
    marginTop: 8,
    marginHorizontal: -10,
    marginBottom: -10,
    paddingVertical: 2,
    paddingHorizontal: 10,
    paddingBottom: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  toolCardExpandRowPressed: { backgroundColor: c.borderMuted },
  toolCardHeader: { fontSize: 13, fontWeight: '600', color: c.textDark, marginBottom: 8, minWidth: 0 },
  toolCardHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 8,
    marginBottom: 8,
  },
  toolCardHeaderMain: { flex: 1, minWidth: 0 },
  toolCardHeaderFilename: { fontSize: 13, fontWeight: '600', color: c.textStrong },
  toolCardHeaderFilenamePlaceholder: { fontSize: 13, fontWeight: '600', color: c.textTertiary },
  toolCardHeaderEditSummary: { fontSize: 11, fontWeight: '500', color: c.textLabel, marginTop: 2 },
  toolCardBodyMuted: { fontSize: 12, color: c.textTertiary, fontStyle: 'italic', marginTop: 6 },
  /** search_engine：与 FlopsDesktop search-engine-card.css 对齐 */
  searchEngineHeaderMain: {
    fontSize: 13,
    fontWeight: '600',
    color: c.textDark,
    lineHeight: 20,
  },
  searchEngineWrap: {
    flexDirection: 'column',
    gap: 10,
  },
  searchEngineQueriesSection: {},
  searchEngineQueriesLine: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'baseline',
    gap: 6,
    rowGap: 6,
  },
  searchEngineQueriesPrefix: {
    fontSize: 12,
    color: c.textDisabled,
    marginRight: 4,
  },
  searchEngineQueryChip: {
    fontSize: 12,
    color: c.textTertiary,
    textDecorationLine: 'underline',
  },
  searchEngineQueryChipOpen: {
    color: c.gray404040,
  },
  searchEngineQueryExpanded: {
    marginTop: 8,
    paddingLeft: 12,
    borderLeftWidth: 2,
    borderLeftColor: c.borderSubtle,
  },
  searchEnginePerQueryList: {
    marginTop: 6,
    paddingTop: 6,
    paddingLeft: 12,
    paddingRight: 8,
    paddingBottom: 8,
    borderTopWidth: 1,
    borderTopColor: c.borderSubtle,
  },
  searchEnginePerQueryItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
    paddingVertical: 4,
  },
  searchEnginePerQueryIndex: {
    fontSize: 11,
    color: c.textDisabled,
    lineHeight: 18,
    minWidth: 18,
  },
  searchEnginePerQueryMain: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  searchEnginePerQueryLink: {
    fontSize: 12,
    fontWeight: '400',
    color: c.textStrong2,
    flexWrap: 'wrap',
  },
  searchEnginePerQueryTitle: {
    fontSize: 12,
    fontWeight: '400',
    color: c.textStrong2,
  },
  searchEnginePerQueryDesc: {
    fontSize: 12,
    color: c.textTertiary,
    lineHeight: 17,
    marginTop: 2,
  },
  searchEngineHero: {
    paddingTop: 6,
    borderTopWidth: 1,
    borderTopColor: c.borderSubtle,
  },
  searchEngineHeroHead: {
    flexDirection: 'row',
    flexWrap: 'nowrap',
    alignItems: 'center',
    gap: 6,
    marginBottom: 8,
    minWidth: 0,
    overflow: 'hidden',
  },
  searchEngineGoalInline: {
    flex: 1,
    minWidth: 0,
    fontSize: 12,
    lineHeight: 17,
    color: c.textTertiary,
  },
  searchEngineHeroSep: {
    flexShrink: 0,
    fontSize: 12,
    color: c.borderD4,
  },
  searchEngineHeroLabelInline: {
    flexShrink: 0,
    fontSize: 12,
    fontWeight: '600',
    color: c.textLabel,
    letterSpacing: 0.3,
  },
  searchEngineHeroGrid: {
    gap: 10,
  },
  searchEngineHeroItem: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: c.surface,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: c.borderCard,
    minWidth: 0,
    gap: 2,
  },
  searchEngineHeroLink: {
    fontSize: 14,
    fontWeight: '500',
    color: c.textStrong2,
    lineHeight: 19,
  },
  searchEngineHeroTitle: {
    fontSize: 14,
    fontWeight: '500',
    color: c.textStrong2,
    lineHeight: 19,
  },
  searchEngineHeroDesc: {
    fontSize: 12,
    color: c.textTertiary,
    lineHeight: 17,
    marginTop: 2,
  },
  searchEngineMuted: {
    fontSize: 13,
    color: c.textTertiary,
    margin: 0,
  },
  searchEngineError: {
    fontSize: 13,
    color: c.dangerDark,
    margin: 0,
  },
  /** 与 Web `.tool-card-write-preview` 半折叠区域一致 */
  fileToolPreviewFullWrap: { marginTop: 8 },
  fileToolPreviewClip: {
    maxHeight: 120,
    marginTop: 8,
    overflow: 'hidden',
    position: 'relative',
  },
  fileToolPreviewScroll: { maxHeight: 120, marginTop: 8 },
  fileToolPreviewScrollContent: { paddingBottom: 4 },
  /** local_exec_command 半折叠：与 Web .tool-card-exec-scroll-preview 类似 */
  execToolPreviewScroll: { maxHeight: 140, marginTop: 6 },
  execToolPreviewScrollContent: { paddingBottom: 6 },
  toolCardExecBody: { marginTop: 4 },
  toolCardExecPrompt: {
    fontSize: 12,
    color: c.textStrong,
    lineHeight: 18,
    marginBottom: 6,
    fontFamily: Platform.select({ ios: 'Menlo', android: 'monospace', default: 'monospace' }),
  },
  toolCardExecPromptPrefix: { color: c.textMutedSlate, fontWeight: '600' as const },
  toolCardExecCwd: { color: c.textTertiary },
  /** 时间在滚动区外，避免输出更新时底栏随 scrollToEnd 抖动 */
  toolCardExecExit: {
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: c.borderMuted,
    fontSize: 11,
    color: c.textMutedSlate,
  },
  fileToolPreviewFade: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 36,
  },
  fileToolPreviewEllipsis: {
    position: 'absolute',
    bottom: 2,
    left: 0,
    right: 0,
    textAlign: 'center',
    fontSize: 12,
    color: c.textTertiary,
  },
  toolCardWritePreview: {},
  toolCardWritePreviewText: { marginTop: 0 },
  toolCardDiff: { flexDirection: 'row', gap: 12, marginTop: 8 },
  toolCardDiffPreview: { marginTop: 0 },
  toolCardDiffSide: { flex: 1, minWidth: 0 },
  toolCardDiffOld: { borderRightWidth: 1, borderRightColor: c.borderMuted, paddingRight: 12 },
  toolCardDiffLabel: { fontSize: 11, fontWeight: '600', color: c.textTertiary, marginBottom: 2 },
  toolCardDiffPre: {
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    fontSize: 12,
    lineHeight: 18,
    color: c.textStrong,
    margin: 0,
  },
  toolCardBody: { fontSize: 13, color: c.textBody, marginTop: 6, lineHeight: 20 },
  toolCardCodeText: {
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    fontSize: 12,
    color: c.textHeader,
    lineHeight: 18,
    marginTop: 6,
  },
  toolCardSafetyMeta: { fontSize: 11, color: c.textMutedSlate, marginTop: 6 },
  toolCardSafetyReason: { fontSize: 12, color: c.textSlate, marginTop: 6 },
  readPagesEntryBox: {
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: c.borderMuted,
  },
  readPagesEntryTitle: { fontSize: 12, fontWeight: '600', color: c.textPrimary },
  readPagesTextBlock: { fontSize: 13, color: c.textBody, lineHeight: 20, marginTop: 6 },
  readPagesErrorText: { fontSize: 12, color: c.dangerTextDark, marginTop: 6 },
  readPagesLinksText: { fontSize: 12, color: c.textSlate, marginTop: 6 },
  readPagesUrlListWrap: { marginTop: 8, gap: 6 },
  readPagesUrlItem: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  readPagesUrlLink: { flex: 1, fontSize: 12, color: c.link },
  readPagesCardsScrollView: { marginTop: 8 },
  readPagesCardsScroll: { paddingVertical: 4, gap: 4 },
  readPagesSmallCard: {
    width: 160,
    backgroundColor: c.toolCardBg,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: c.borderD8,
    overflow: 'hidden',
    marginRight: 6,
  },
  readPagesSmallCardHeader: {
    position: 'relative',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 6,
    backgroundColor: c.toolInnerSurface2,
    borderBottomWidth: 1,
    borderBottomColor: c.borderD5,
  },
  readPagesSmallCardHeaderStreaming: {
    borderBottomWidth: 0,
    paddingBottom: 9,
  },
  readPagesHeaderLoadBarTrack: {
    position: 'absolute',
    left: 8,
    right: 8,
    bottom: 0,
    height: 2,
    backgroundColor: c.readPagesTrackBg,
    borderRadius: 2,
    overflow: 'hidden',
  },
  readPagesHeaderLoadBarBar: {
    position: 'absolute',
    left: 0,
    top: 0,
    width: 56,
    height: 2,
    backgroundColor: c.accentPurple,
    borderRadius: 2,
  },
  readPagesSmallCardTitle: { flex: 1, fontSize: 11, fontWeight: '600', color: c.textStrong, minWidth: 0 },
  readPagesSmallCardBodyWrap: {
    width: '100%',
    aspectRatio: 1,
    minHeight: 0,
    overflow: 'hidden',
  },
  readPagesCardSquare: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: c.toolInnerSurface3,
  },
  readPagesCardSquareBody: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: c.toolCardBg,
  },
  readPagesCardSquareCenter: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  readPagesCardBodyScroll: {
    padding: 8,
    paddingBottom: 12,
  },
  readPagesCardThumb: { width: '100%', aspectRatio: 1, backgroundColor: c.toolInnerSurface4 },
  readPagesCardSpinner: { marginVertical: 20 },
  toolCardSafetyAdvice: {
    fontSize: 12,
    marginTop: 10,
    padding: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: c.borderMuted,
    backgroundColor: c.toolInnerSurface6,
  },
  toolCardSafetyAdviceDanger: {
    color: c.dangerTextDark,
    backgroundColor: c.roseBg,
    borderColor: c.roseBorder,
  },
  safetyActions: { flexDirection: 'row', gap: 8, marginTop: 8 },
  safetyBtn: { paddingVertical: 6, paddingHorizontal: 12, borderRadius: 6, backgroundColor: c.border },
  safetyBtnPrimary: { backgroundColor: c.primary },
  safetyBtnText: { color: c.textSecondary, fontSize: 14 },
  safetyBtnPrimaryText: { color: c.onPrimary, fontSize: 14 },
  cursorAgentWrap: { marginTop: 8, gap: 14 },
  cursorAgentPromptCard: {
    padding: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: c.border,
    backgroundColor: c.backgroundSecondary,
  },
  cursorAgentPromptLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: c.textMuted,
    marginBottom: 8,
    letterSpacing: 0.4,
  },
  cursorAgentPromptText: { fontSize: 14, lineHeight: 22, color: c.textPrimary },
  cursorAgentPromptMeta: { fontSize: 12, color: c.textMuted, marginTop: 10 },
  cursorAgentReply: {
    padding: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: c.borderMuted,
    backgroundColor: c.surface,
  },
  cursorAgentReplyLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: c.textLabel,
    marginBottom: 10,
    letterSpacing: 0.4,
  },
  cursorAgentReplyBody: { marginTop: 4 },
  cursorAgentReplyLoading: { fontSize: 13, color: c.textMuted, fontStyle: 'italic' },
  cursorAgentReplyEmpty: { fontSize: 13, color: c.textMuted, fontStyle: 'italic' },
  cursorAgentReplyError: {
    fontSize: 13,
    color: c.dangerDark,
    backgroundColor: c.errorBg,
    padding: 8,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: c.roseBorderStrong,
  },
  composerInput: {
    flex: 1,
    backgroundColor: c.inputBg,
    borderWidth: 1,
    borderColor: c.hairlineBorder,
    borderRadius: 28,
    paddingHorizontal: 20,
    paddingVertical: 14,
    fontSize: 16,
    color: c.textPrimary,
    ...(Platform.OS === 'ios' ? shadowSoft : {}),
  },
  sendBtn: {
    width: 52,
    height: 52,
    borderRadius: 28,
    backgroundColor: c.primary,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 0,
    overflow: 'hidden',
    ...(Platform.OS === 'ios' ? shadowFab : {}),
  },
  sendBtnStop: { backgroundColor: c.danger },
  sendBtnDisabled: { opacity: 0.5 },
  });
}
